apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telemetry-client
  labels:
    app: telemetry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: telemetry-client
  template:
    metadata:
      labels:
        app: telemetry-client
    spec:
      containers:
      - name: telemetry-app
        image: fjur/telemetry_client:latest
        ports:
        - containerPort: 50051